# Name and timezone
name = "Yes"
icon = "../assets/spinner.png"
timezone = "Europe/London"

# Heliactyl release information
version = "10.0.0"

# Additional settings
testing = false
clusters = 1
database = "sqlite://heliactyl3.db"

# Pterodactyl settings
[pterodactyl]
domain = "https://panel.example.com"
key = "ptla_"

# Webserver
[website]
port = 3_001
secret = "secret"
discord = "https://discord.gg/example"
coins = "Coins"
# Color was supposed to be here, but due to tailwind issues, we're unable to do that.

# Module settings (formerly API)
[api.client]
accountSwitcher = true

  [api.client.api]
  enabled = false
  code = "asdasdasdasd"

  [api.client.j4r]
  enabled = false

    [[api.client.j4r.ads]]
    name = "Example server 1"
    invite = "https://discord.gg/example"
    id = "000000000000000000"
    coins = 200

    [[api.client.j4r.ads]]
    name = "Example server 2"
    invite = "https://discord.gg/example"
    id = "000000000000000000"
    coins = 200

  [api.client.bot]
  token = ""

    [api.client.bot.joinguild]
    _comment = "The Discord bot must be in these servers and have invite permissions. Automatic guild joining will not work unless role packages are configured correctly. You can always just set it to a random role & package so that only this works."
    enabled = true
    guildid = [ "" ]

    [api.client.bot.giverole]
    _comment = "Auto-join must be enabled for this to work - or the user must already be in your Discord. This will give the user a role when they login."
    enabled = false
    guildid = "your server id goes here mate"
    roleid = "your role id goes here mate"

  [api.client.passwordgenerator]
  signup = true
  note = "Use this to disable registering on Heliactyl."
  length = 24

  [api.client.allow]
  newusers = true
  regen = true
  overresourcessuspend = false

    [api.client.allow.server]
    create = true
    modify = true
    delete = true

  [api.client.oauth2]
  _comment = "Go to https://discord.dev/ and create an application to set up OAuth2. This is required for Heliactyl to work. You must also set the redirect URL to the link below."
  id = ""
  secret = ""
  link = "http://localhost:3001"
  callbackpath = "/callback"
  prompt = true

    [api.client.oauth2.ip]
    "trust x-forwarded-for" = true
    block = [ ]
    "duplicate check" = false
    _note = "Anti-alt checks will not work if you are proxying through Cloudflare. This is due to the fact that Cloudflare does not pass the real IP address through the headers. If you are using Cloudflare, please disable this feature."

  [api.client.ratelimits]
  "/callback" = 2
  "/create" = 1
  "/delete" = 1
  "/modify" = 1
  "/updateinfo" = 1
  "/setplan" = 2
  "/admin" = 1
  "/regen" = 1
  "/renew" = 1
  "/api/userinfo" = 1

  [api.client.packages]
  default = "default"

# Packages
[api.client.packages.list.default]
ram = 3_072
disk = 5_120
cpu = 150
servers = 4

    [api.client.packages.rolePackages]
    note = "This allows you to set a different plan/package to people who have a specific role however this requires the Discord bot to be configured and functioning. This is mainly used for Boost rewards."
    roleServer = ""

      [api.client.packages.rolePackages.roles]

[api.client.locations.1]
name = "United States"
iso = "US"
pro = false
show = true

[api.client.eggs.purpur]
pro = false
display = "Minecraft - Purpur"

  [api.client.eggs.purpur.minimum]
  ram = 1_024
  disk = 1_024
  cpu = 100

  [api.client.eggs.purpur.maximum]
  ram = 6_144
  disk = 20_480
  cpu = 400

  [api.client.eggs.purpur.info]
  egg = 5
  docker_image = "ghcr.io/zenllc/java:21"
  startup = "java -Xms256M -Xmx{{SERVER_MEMORY}}M {{JAVA_ARGUMENTS}} -jar {{SERVER_JARFILE}}"

    [api.client.eggs.purpur.info.environment]
    SERVER_JARFILE = "server.jar"
    BUILD_NUMBER = "latest"
    JAVA_ARGUMENTS = "--add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs/ -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"

    [api.client.eggs.purpur.info.feature_limits]
    databases = 4
    backups = 4

[api.client.eggs.velocity]
pro = false
display = "Velocity"

  [api.client.eggs.velocity.minimum]
  ram = 512
  disk = 128
  cpu = 50

  [api.client.eggs.velocity.maximum]
  ram = 1_024
  disk = 1_024
  cpu = 125

  [api.client.eggs.velocity.info]
  egg = 16
  docker_image = "ghcr.io/zenllc/java:21"
  startup = "java -Xms128M -Xmx{{SERVER_MEMORY}}M {{JAVA_ARGUMENTS}} -jar {{SERVER_JARFILE}}"

    [api.client.eggs.velocity.info.environment]
    SERVER_JARFILE = "server.jar"
    VELOCITY_VERSION = "latest"
    JAVA_ARGUMENTS = "-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15"
    BUILD_NUMBER = "latest"

    [api.client.eggs.velocity.info.feature_limits]
    databases = 4
    backups = 4

[api.client.eggs.vanillabugrock]
pro = false
display = "Vanilla Bedrock"

  [api.client.eggs.vanillabugrock.minimum]
  ram = 512
  disk = 128
  cpu = 50

  [api.client.eggs.vanillabugrock.maximum]
  ram = 6_144
  disk = 20_480
  cpu = 400

  [api.client.eggs.vanillabugrock.info]
  egg = 17
  docker_image = "ghcr.io/parkervcp/yolks:debian"
  startup = "./bedrock_server"

    [api.client.eggs.vanillabugrock.info.environment]
    BEDROCK_VERSION = "latest"
    LD_LIBRARY_PATH = "."
    SERVERNAME = "Server"
    GAMEMODE = "survival"
    DIFFICULTY = "easy"
    CHEATS = "false"

    [api.client.eggs.vanillabugrock.info.feature_limits]
    databases = 4
    backups = 4

[api.client.eggs.pmmpbugrock]
pro = false
display = "PocketMineMP"

  [api.client.eggs.pmmpbugrock.minimum]
  ram = 512
  disk = 128
  cpu = 50

  [api.client.eggs.pmmpbugrock.maximum]
  ram = 6_144
  disk = 20_480
  cpu = 400

  [api.client.eggs.pmmpbugrock.info]
  egg = 21
  docker_image = "ghcr.io/parkervcp/yolks:debian"
  startup = "./bin/php7/bin/php ./PocketMine-MP.phar --no-wizard"

    [api.client.eggs.pmmpbugrock.info.environment]
    VERSION = "PM5"

    [api.client.eggs.pmmpbugrock.info.feature_limits]
    databases = 4
    backups = 4

  [api.client.coins]
  enabled = true
  dailyReward = 150

    [api.client.coins.store]
    enabled = true

      [api.client.coins.store.ram]
      cost = 1750
      per = 1_024 # do not change

      [api.client.coins.store.disk]
      cost = 750
      per = 2_048 # do not change

      [api.client.coins.store.cpu]
      cost = 2000
      per = 100 # do not change

      [api.client.coins.store.servers]
      cost = 750
      per = 1 # do not change

[api.afk]
path = "ws"
every = 60
coins = 2.0
enabled = true

[linkvertise]
enabled = true
coins = 150
userid = "000000"

[antivpn]
note = "For this to work, generate an API Key on https://proxycheck.io/. If you do not put a key, Heliactyl will automatically disable anti-VPN."
status = false
APIKey = "Proxycheck API Key"
whitelistedIPs = [ "IP address" ]

[whitelist]
note = "This allows only specific people to be able to login to the Heliactyl dashboard. This does not affect your Panel."
status = false
users = [ "User ID" ]

[logging]
_note = "This is the 2nd-generation version of Heliactyl's logging system. Please report any bugs on the GitHub (github.com/heliactyloss/heliactyl). Thank you."
status = true
webhook = ""

[logging.actions.user]
signup = true
"create server" = true
"gifted coins" = true
"modify server" = true
"buy servers" = true
"buy ram" = true
"buy cpu" = true
"buy disk" = true

[logging.actions.admin]
"set coins" = true
"add coins" = true
"set resources" = true
"set plan" = true
"create coupon" = true
"revoke coupon" = true
"remove account" = true
"view ip" = true
